

name: Delete S3 bucket after PR merge

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Clean up temperory bucket
      id: docker-run-test
      uses: ./
