
# It will create `$AWS_S3_BUCKET.auto-deploy` s3 bucket and build the react app
# and Deploy it

name: Deploy prebuild static site

on:
  push:
    branches:
    - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy prebuild static app
      uses: razzkumar/pr-automation-with-s3@v0.4.0
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}   # attach auto-deploy on name while creating s3 bucket
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        IS_BUILD: 'false'            # It doesn't run "yarn build"
        SRC_FOLDER: "public"       # Optional: It will take "build" folder by default
        ACTION: 'deploy'             # action must be deploy
