name: Create s3 bucket and deploy static site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Checking what is happining
      id: action-test
      uses: ./
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Print URL
      if: steps.action-test.outputs.url != ''
      run: echo ${{ steps.action-test.outputs.url }}
